#!/bin/bash

if [ "x$NDK_DIR" == "x" ]; then
	echo "NDK_DIR env variable not set"
	exit 1
fi

$NDK_DIR/ndk-build

if [ $? -eq 0 ]; then
	declare -A PATHS='([armeabi]="armv5" [armeabi-v7a]="armv7" [mips]="mips" [x86]="x86")'
	FILES=( 'iptables' 'tcproxy' 'grep' )

	for fpath in "${!PATHS[@]}"; do
		suffix="${PATHS[$fpath]}"
		for file in "${FILES[@]}"; do
			dest="src/main/res/raw/${file}_${suffix}"
			ls -l libs/$fpath/$file
			cp libs/$fpath/$file $dest
			rm ${dest}.zip
			zip -r $dest $dest
			rm $dest
		done
	done
fi
